# Generated by Django 5.1.6 on 2025-02-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlar',
            options={'verbose_name_plural': 'postlar'},
        ),
        migrations.AlterModelTable(
            name='postlar',
            table='postlar',
        ),
    ]
