# Generated by Django 5.1.6 on 2025-02-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_alter_postlar_options_alter_postlar_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('content_small', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
