# Generated by Django 5.1.6 on 2025-02-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Izohlar',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='postlar',
        ),
    ]
