# Generated by Django 5.1.6 on 2025-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('izoh', models.CharField(max_length=100)),
                ('batafsil', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
