# Generated by Django 5.1.6 on 2025-02-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('izoh', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'yangiliklar',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='izoh',
            field=models.CharField(max_length=10000),
        ),
    ]
