# Generated by Django 5.1.6 on 2025-02-25 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_yangiliklar_alter_news_izoh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ma'lumot yo'nalishlari", max_length=100, verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='kontakt')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Postlar',
        ),
        migrations.DeleteModel(
            name='Yangiliklar',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time'], 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='batafsil',
        ),
        migrations.RemoveField(
            model_name='news',
            name='izoh',
        ),
        migrations.RemoveField(
            model_name='news',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rasmi',
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='', max_length=1000, verbose_name='Asosiy qismi'),
        ),
        migrations.AddField(
            model_name='news',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='media/images/05.jpg', upload_to='news/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='asdfasdf', help_text="o'zi to'ldiriladi", max_length=250, verbose_name='url shakli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PD', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='asdfasdf', help_text='Title of the news', max_length=250, verbose_name='xabar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
