# Generated by Django 5.1.6 on 2025-02-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0008_category_contact_delete_postlar_delete_yangiliklar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categoriy',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baza.category'),
            preserve_default=False,
        ),
    ]
