# Generated by Django 5.1.6 on 2025-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0009_news_categoriy'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
