# Generated by Django 5.1.6 on 2025-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0010_news_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='update_time',
        ),
        migrations.AddField(
            model_name='news',
            name='test',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
