# Generated by Django 5.1.6 on 2025-02-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0013_news_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='test',
        ),
    ]
