# Generated by Django 5.1.6 on 2025-02-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0014_remove_news_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='news',
            name='body2',
            field=models.TextField(default='', max_length=1000, verbose_name='Asosiy qismi'),
        ),
        migrations.AddField(
            model_name='news',
            name='body3',
            field=models.TextField(default='', max_length=1000, verbose_name='Asosiy qismi'),
        ),
    ]
