# Generated by Django 5.1.6 on 2025-03-01 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0015_rename_body_news_body1_news_body2_news_body3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body1',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body3',
        ),
        migrations.CreateModel(
            name='Postlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='title of the news', max_length=250, verbose_name='url shakli')),
                ('slug', models.SlugField(help_text="o'zi to'ldiriladi", max_length=250, verbose_name='url shakli')),
                ('image', models.ImageField(upload_to='posts/images')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PD', 'Published')], default='DF', max_length=2)),
                ('categoriy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.category')),
            ],
            options={
                'verbose_name_plural': 'Postlar',
                'ordering': ['-publish_time'],
            },
        ),
    ]
