# Generated by Django 5.1.6 on 2025-03-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0017_alter_postlar_nomi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postlar',
        ),
    ]
